spring:
  datasource:
#    url: jdbc:mariadb://localhost:3306/bongyang_club
    url: jdbc:mysql://localhost:3306/bongyang_club
    username: root
    password: 1234
#    driver-class-name: org.mariadb.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

jwt:
  secret:
    key: eoguddleoguddleoguddleoguddleoguddleoguddleoguddleoguddleoguddleoguddleoguddleoguddleoguddleoguddleoguddl